- hosts: all
  become: true
  vars:
    allowed_ssh_networks:
      - 192.168.56.0/24
      - 10.0.2.0/24

    unnecessary_services:
      - postfix
      - telnet
    unnecessary_software:
      - tcpdump
      - nmap
      - wpasupplicant

  tasks:
    - name: Perform full patching
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Add admin group
      group:
        name: admin
        state: present

    - name: Add local user
      user:
        name: admin
        group: admin
        shell: /bin/bash
        home: /home/admin
        createhome: yes
        state: present

    - name: Add SSH public key for user
      authorized_key:
        user: admin
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: Add sudoer rule for local user
      copy:
        dest: /etc/sudoers.d/admin
        src: etc/sudoers.d/admin
        owner: root
        group: root
        mode: 0440
        validate: /usr/sbin/visudo -csf %s

    - name: Add SSH port to internal zone
      ufw:
        rule: allow
        port: ssh
        state: enabled
      become: true

    - name: Add permitted networks to internal zone
      ufw:
        rule: allow
        proto: tcp
        from_ip: "{{ item }}"
        state: enabled
      become: true
      with_items: "{{ allowed_ssh_networks }}"

    - name: Drop ssh from the public zone
      ufw:
        rule: deny
        port: ssh
      become: true



    - name: Remove undesirable packages
      apt:
        name: "{{ unnecessary_software }}"
        state: absent


    - name: Stop and disable unnecessary services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items: "{{ unnecessary_services }}"
      ignore_errors: yes



    - name: Set a message of the day
      copy:
        dest: /etc/motd
        src: etc/motd
        owner: root
        group: root
        mode: 0644

    - name: Set a login banner
      copy:
        dest: "{{ item }}"
        src: etc/issue
        owner: root
        group: root
        mode: 0644
      with_items:
        - /etc/issue
        - /etc/issue.net

  handlers:
    - name: Reload SSH
      service:
        name: sshd
        state: reloaded
